# Site settings
title: Tetzlaff Decorative Masonry
email: your-email@domain.com
description: "Tetzlaff Decorative Masonry"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
